### ISSUE TITLE
Making LibCSP a git submodule

### ISSUE THREAD

**Issue by aminya** [IrisSat/IrisSat-Flight-Software#13]
I think we should make the following directory a submodule. This makes it easier to see what's going on.
mbsat-fsw-softconsole/Libraries/CSP/

Here is the @joehowarth17's fork of libcsp
https://github.com/joehowarth17/libcsp

My comparison of the fork and the folder shows these differences:
1) libcsp.a is different: the binary file
2) include/csp/csp_autoconfig.h is different:

The right side is the folder of this repo, and the left side is the fork.
![image](https://user-images.githubusercontent.com/16418197/99841438-c9914780-2b33-11eb-8e8f-0a973b73a7e4.png)

Here is the git history of this directory for reference:
https://github.com/IrisSat/IrisSat-Flight-Software/commits/master/mbsat-fsw-softconsole/Libraries/CSP

**Comment by joehowarth17** [comment]
This is a good idea! I'll transfer the repository to the IrisSat org.
The differences you showed are because the .a static library file and csp_autconfig file are generated when you build the library, so I didn't included them in the libcsp repo but they show up in the actual project.

By including this as a submodule, I'll need to update the project includes since I was manually moving files around before and the library file will be in a different location and there is a whole bunch of files to ignore. Also I will need to modify the build script.

Also I think we should make it more clear in the main readme, that this library must now be built before the project will run.

I can make these changes and make sure the project compiles, and then I'll add the commits to #12  so that all the re-organization is in one PR.

**Comment by aminya** [comment]
Thanks, Joseph. The less code we have to deal with in this repository, the easier it would be to wrap our heads around it.

Ideally, we should make all the "vendor" libraries and drivers a git submodule. Or if we want to keep things in the repository, we should have empty files in the root of the folder that shows that these files are vendored or auto-generated. For example,
```
.auto-generated
.vendor-lib
.vendor-driver
``` 
This prevents warns people not to edit those.

**Comment by aminya** [comment]
I moved my suggestion to a separate issue, so we can close this issue by merging #12
